export const actionTypes = {
    SET_CATEGORY : "SET_CATEGORY",
    SELECTED_CATEGORIES: "SELECTED_CATEGORIES",
    SELECTED_CATEGORY: "SELECTED_CATEGORY",
    REMOVE_SELECTED_CATEGORY: "REMOVE_SELECTED_CATEGORY",
    SET_RESTAURANTS: "SET_RESTAURANTS"
}