import { FormBase } from 'core/components';

export default class ContributionEditForm extends FormBase {
    constructor(hooks) {
        super(hooks);
    }

    setup() {
        return {
            fields: [
                'id',
                'donorAccountId',
                'amount',
                'description',
                'paymentTypeId',
                'bankAccountId',
                'checkNumber',
                'payerInformation',
                'payerInformation.firstName',
                'payerInformation.lastName',
                'payerInformation.address',
                'payerInformation.address.id',
                'payerInformation.address.addressLine1',
                'payerInformation.address.addressLine2',
                'payerInformation.address.city',
                'payerInformation.address.state',
                'payerInformation.address.zipCode',
                'payerInformation.emailAddress',
                'payerInformation.emailAddress.id',
                'payerInformation.emailAddress.email',
                'payerInformation.phoneNumber',
                'payerInformation.phoneNumber.id',
                'payerInformation.phoneNumber.number',
                'financialInstitution',
                'financialInstitutionAddressLine1',
                'financialInstitutionAddressLine2',
                'financialInstitutionCity',
                'financialInstitutionState',
                'financialInstitutionZipCode',
                'financialInstitutionPhoneNumber',
                'accountNumber',
                'securityType',
                'securitySymbol',
                'numberOfShares',
                'estimatedValue',
                'transactionId',
                'memo'
            ],

            labels: {
                'amount': 'Amount',
                'description': 'Description',
                'paymentTypeId': 'Payment Type',
                'bankAccountId': 'Bank Account',
                'checkNumber': 'Check Number',
                'payerInformation': 'Payer Information',
                'payerInformation.firstName': 'Payer First Name',
                'payerInformation.lastName': 'Payer Last Name',
                'payerInformation.address': 'Payer Address',
                'payerInformation.address.addressLine1': 'Payer Address Line 1',
                'payerInformation.address.addressLine2': 'Payer Address Line 2',
                'payerInformation.address.city': 'Payer City',
                'payerInformation.address.state': 'Payer State',
                'payerInformation.address.zipCode': 'Payer Zip Code',
                'payerInformation.emailAddress': 'Payer Email Address',
                'payerInformation.emailAddress.email': 'Payer Email',
                'payerInformation.phoneNumber': 'Payer Phone Number',
                'payerInformation.phoneNumber.number': 'Payer Number',
                'financialInstitution': 'Financial Institution',
                'financialInstitutionAddressLine1': 'Address Line 1',
                'financialInstitutionAddressLine2': 'Address Line 2',
                'financialInstitutionCity': 'Address City',
                'financialInstitutionState': 'Address State',
                'financialInstitutionZipCode': 'Address Zip Code',
                'financialInstitutionPhoneNumber': 'Phone Number',
                'accountNumber': 'Account Number',
                'securityType': 'Security Type',
                'numberOfShares': 'Number Of Shares',
                'securitySymbol': 'Security Symbol',
                'estimatedValue': 'Estimated Value',
                'transactionId': 'Transaction Id',
                'memo': 'Memo',
            },

            placeholders: {
                'amount': 'Enter Amount',
                'description': 'Enter Description',
                'paymentTypeId': 'Choose Payment Type',
                'bankAccountId': 'Choose Bank Account',
                'checkNumber': 'Enter Check Number',
                'payerInformation.firstName': 'Enter Payer First Name',
                'payerInformation.lastName': 'Enter Payer Last Name',
                'payerInformation.address.addressLine1': 'Enter Payer Address Line 1',
                'payerInformation.address.addressLine2': 'Enter Payer Address Line 2',
                'payerInformation.address.city': 'Enter Payer City',
                'payerInformation.address.state': 'Enter Payer State',
                'payerInformation.address.zipCode': 'Enter Payer Zip Code',
                'payerInformation.emailAddress.email': 'Enter Payer Email',
                'payerInformation.phoneNumber.number': 'Enter Payer Number',
                'financialInstitution': 'Enter Financial Institution Name',
                'financialInstitutionAddressLine1': 'Enter Address Line 1',
                'financialInstitutionAddressLine2': 'Enter Address Line 2',
                'financialInstitutionCity': 'Enter Address City',
                'financialInstitutionState': 'Enter Address State',
                'financialInstitutionZipCode': 'Enter Address Zip Code',
                'financialInstitutionPhoneNumber': 'Enter Phone Number',
                'accountNumber': 'Enter Account Number',
                'securityType': 'Enter Security Type',
                'numberOfShares': 'Enter Number Of Shares',
                'estimatedValue': 'Enter Estimated Value',
                'securitySymbol': 'Enter Security Symbol',
                'transactionId': 'Enter Transaction Id',
                'memo': 'Enter Memo',
            },

            rules: {
                'id': 'required|string',
                'donorAccountId': 'required|string',
                'amount': 'required|numeric|min:0',
                'description': 'string',
                'paymentTypeId': 'required|string',
                'bankAccountId': 'string',
                'checkNumber': 'string',
                'payerInformation.firstName': 'required|string',
                'payerInformation.lastName': 'required|string',
                'payerInformation.address.addressLine1': 'required|string',
                'payerInformation.address.addressLine2': 'string',
                'payerInformation.address.city': 'required|string',
                'payerInformation.address.state': 'required|string',
                'payerInformation.address.zipCode': 'required|string',
                'payerInformation.emailAddress.email': 'required|string',
                'payerInformation.phoneNumber.number': 'required|string',
                'financialInstitution': 'string',
                'financialInstitutionAddressLine1': 'required_with:financialInstitutionCity|required_with:financialInstitutionState|required_with:financialInstitutionZipCode|string',
                'financialInstitutionAddressLine2': 'string',
                'financialInstitutionCity': 'required_with:financialInstitutionAddressLine1|string',
                'financialInstitutionState': 'required_with:financialInstitutionAddressLine1|string',
                'financialInstitutionZipCode': 'required_with:financialInstitutionAddressLine1|string',
                'financialInstitutionPhoneNumber': 'string',
                'accountNumber': 'string',
                'securityType': 'string',
                'numberOfShares': 'numeric|min:0',
                'estimatedValue': 'numeric|min:10000',
                'securitySymbol': 'string',
                'transactionId': 'string',
                'memo': 'string',
            }
        };
    }
}
