export { default as LoginTemplate } from './LoginTemplate';
export { default as RegisterTemplate } from './RegisterPublicTemplate';
export { default as RegisterPublicTemplate } from './RegisterPublicTemplate';
export { default as ActivationConfirmTemplate } from './ActivationConfirmTemplate';
export { default as RegistrationSuccessTemplate } from './RegistrationSuccessTemplate';
export { default as PasswordRecoveryTemplate } from './PasswordRecoveryTemplate';
export { default as PasswordChangeTemplate } from './PasswordChangeTemplate';
export { default as UnauthorizedTemplate } from './UnauthorizedTemplate';
export { default as UserPreferencesTemplate } from './UserPreferencesTemplate';
