export { default as CharityAddressListTableTemplate } from './CharityAddressListTableTemplate'
export { default as CharityBankAccountTemplate } from './CharityBankAccountTemplate'
export { default as CharityGeneralDataTemplate } from './CharityGeneralDataTemplate'
export { default as CharityAdvancedSearchTemplate } from './CharityAdvancedSearchTemplate'
export { default as CharityWithdrawFundTemplate } from './CharityWithdrawFundTemplate'
export { default as CharityPaymentOptionsTemplate } from './CharityPaymentOptionsTemplate'
export { default as SelectCharityTemplate } from './SelectCharityTemplate'