export { default as ActivityTabTemplate } from './ActivityTabTemplate'
export { default as AllTransactionListTemplate } from './AllTransactionListTemplate'
export { default as GrantsListTemplate } from './GrantsListTemplate'
export { default as RemoteDepositListTemplate } from './remoteDepositListTemplate'
export { default as PaymentsListTemplate } from './PaymentsListTemplate'
export { default as DepositsInsightTemplate } from './DepositsInsightTemplate'
export { default as CharityWithdrawListTemplate } from  './CharityWithdrawListTemplate'