import { FormBase } from 'core/components';

export default class DonorAccountCreateForm extends FormBase {
    constructor(hooks) {
        super(hooks);
    }

    setup() {
        return {
            fields: [
                'isCompany',
                'accountTypeId',
                'fundName',
                'activationUrl',
                'securityPin',
                'deliveryMethodTypeId',
                'coreUser.prefixTypeId',
                'coreUser.firstName',
                'coreUser.middleName',
                'coreUser.lastName',
                'coreUser.userName',
                'coreUser.coreMembership.password',
                'coreUser.coreMembership.confirmPassword',
                'companyProfile.name',
                'companyProfile.dba',
                'companyProfile.website',
                'companyProfile.businessTypeId',
                'companyProfile.address.addressLine1',
                'companyProfile.address.addressLine2',
                'companyProfile.address.city',
                'companyProfile.address.state',
                'companyProfile.address.zipCode',
                'companyProfile.emailAddress.email',
                'companyProfile.phoneNumber.number',
                'address.addressLine1',
                'address.addressLine2',
                'address.city',
                'address.state',
                'address.zipCode',
                'emailAddress.email',
                'phoneNumber.number',
                'initialContribution',
                'contributionMinimumInitial',
                'contributionMinimumAdditional',
                'grantMinimumAmount',
                'grantFee',
                'certificateDeduction',
                'certificateFee',
                'extraBookletPercentage',
                'lineOfCredit',
                'blankBookletMax',
                'notificationLimitRemainderAmount',
                'sendWelcomeEmail',
                'isApproved'
            ],

            labels: {
                'isCompany': 'Company Account?',
                'accountTypeId': 'Activation Type',
                'fundName': 'Fund Name',
                'deliveryMethodTypeId': 'Delivery Method Type',
                'securityPin': 'Security Pin',
                'coreUser.prefixTypeId': 'Prefix Type',
                'coreUser.firstName': 'First Name',
                'coreUser.middleName': 'Middle Name',
                'coreUser.lastName': 'Last Name',
                'coreUser.userName': 'User Name',
                'coreUser.coreMembership.password': 'Password',
                'coreUser.coreMembership.confirmPassword': 'Confirm Password',
                'companyProfile.name': 'Company Name',
                'companyProfile.dba': 'DBA',
                'companyProfile.website': 'Website',
                'companyProfile.businessTypeId': 'Business Type',
                'companyProfile.address.addressLine1': 'Address Line 1',
                'companyProfile.address.addressLine2': 'Address Line 2',
                'companyProfile.address.city': 'City',
                'companyProfile.address.state': 'State',
                'companyProfile.address.zipCode': 'Zip Code',
                'companyProfile.emailAddress.email': 'Email',
                'companyProfile.emailAddress.description': 'Email Description',
                'companyProfile.phoneNumber.number': 'Number',
                'companyProfile.phoneNumber.description': 'Number Description',
                'donorAccountAddresses': 'Addresses',
                'address.addressLine1': 'Address Line 1',
                'address.addressLine2': 'Address Line 2',
                'address.city': 'City',
                'address.state': 'State',
                'address.zipCode': 'Zip Code',
                'address.description': 'Description',
                'emailAddress.email': 'Email',
                'emailAddress.description': 'Email Description',
                'phoneNumber.number': 'Number',
                'phoneNumber.description': 'Number Description',
                'initialContribution': 'Initial Contribution',
                'contributionMinimumInitial': 'Minimum Initial Contribution',
                'contributionMinimumAdditional': 'Minimum Additional Contribution',
                'grantMinimumAmount': 'Minimum Grant',
                'grantFee': 'Grant Fee',
                'certificateDeduction': 'Certificate Deduction',
                'certificateFee': 'Certificate Fee',
                'extraBookletPercentage': 'Extra Booklet Percentage',
                'lineOfCredit': 'Line Of Credit',
                'blankBookletMax': 'Blank Booklet Max Amount',
                'notificationLimitRemainderAmount': 'Notification Limit Remainder Amount',
                'sendWelcomeEmail': 'Send Welcome Email',
                'isApproved': 'Approved'
            },

            placeholders: {
                'isCompany': 'Company Account?',
                'accountTypeId': 'Select Activation Type',
                'fundName': 'Enter Fund Name',
                'securityPin': 'Enter Security Pin',
                'coreUser.prefixTypeId': 'Select Prefix Type',
                'coreUser.firstName': 'Enter First Name',
                'coreUser.middleName': 'Enter Middle Name',
                'coreUser.lastName': 'Enter Last Name',
                'coreUser.userName': 'Enter User Name',
                'coreUser.coreMembership.password': 'Enter Password',
                'coreUser.coreMembership.confirmPassword': 'Enter Confirm Password',
                'companyProfile.name': 'Enter Company Name',
                'companyProfile.dba': 'Enter DBA',
                'companyProfile.website': 'Enter Website',
                'companyProfile.businessTypeId': 'Select Business Type',
                'companyProfile.address.addressLine1': 'Enter Address Line 1',
                'companyProfile.address.addressLine2': 'Enter Address Line 2',
                'companyProfile.address.city': 'Enter City',
                'companyProfile.address.state': 'Enter State',
                'companyProfile.address.zipCode': 'Enter Zip Code',
                'companyProfile.emailAddress.email': 'Enter Email',
                'companyProfile.emailAddress.description': 'Enter Email Description',
                'companyProfile.phoneNumber.number': 'Enter Number',
                'companyProfile.phoneNumber.description': 'Enter Number Description',
                'address.addressLine1': 'Enter Address Line 1',
                'address.addressLine2': 'Enter Address Line 2',
                'address.city': 'Enter City',
                'address.state': 'Enter State',
                'address.zipCode': 'Enter Zip Code',
                'address.description': 'Enter Description',
                'emailAddress.email': 'Enter Email',
                'emailAddress.description': 'Enter Email Description',
                'phoneNumber.number': 'Enter Number',
                'phoneNumber.description': 'Enter Number Description',
                'initialContribution': 'Initial Contribution',
                'contributionMinimumInitial': 'Enter Minimum Initial Contribution',
                'contributionMinimumAdditional': 'Enter Minimum Additional Contribution',
                'grantMinimumAmount': 'Enter Minimum Grant',
                'grantFee': 'Enter Grant Fee',
                'certificateDeduction': 'Enter Certificate Deduction',
                'certificateFee': 'Enter Certificate Fee',
                'extraBookletPercentage': 'Enter Extra Booklet Percentage',
                'lineOfCredit': 'Enter Line Of Credit',
                'blankBookletMax': 'Enter Blank Booklet Max Amount',
                'notificationLimitRemainderAmount': 'Enter Notification Limit Remainder Amount',
                'sendWelcomeEmail': 'Send Welcome Email',
                'isApproved': 'Approved'
            },

            rules: {
                'isCompany': 'required|boolean',
                'accountTypeId': 'required|string',
                'fundName': 'required|string',
                'securityPin': 'required|numeric|digits:4',
                'coreUser.prefixTypeId': 'string',
                'coreUser.firstName': 'required|string',
                'coreUser.middleName': 'string',
                'coreUser.lastName': 'required|string',
                'coreUser.userName': 'required|string',
                'coreUser.coreMembership.password': 'required|string',
                'coreUser.coreMembership.confirmPassword': 'required|string',
                'companyProfile.name': 'required_if:isCompany,true|string',
                'companyProfile.dba': 'string',
                'companyProfile.website': 'string',
                'companyProfile.businessTypeId': 'required_if:isCompany,true|string',
                'companyProfile.address.addressLine1': 'required_if:isCompany,true|string',
                'companyProfile.address.addressLine2': 'string',
                'companyProfile.address.city': 'required_if:isCompany,true|string',
                'companyProfile.address.state': 'required_if:isCompany,true|string',
                'companyProfile.address.zipCode': 'required_if:isCompany,true|string',
                'companyProfile.emailAddress.email': 'required_if:isCompany,true|string',
                'companyProfile.emailAddress.description': 'string',
                'companyProfile.phoneNumber.number': 'required_if:isCompany,true|string',
                'companyProfile.phoneNumber.description': 'string',
                'address.addressLine1': 'required|string',
                'address.addressLine2': 'string',
                'address.city': 'required|string',
                'address.state': 'required|string',
                'address.zipCode': 'required|string',
                'address.description': 'string',
                'emailAddress.email': 'required|email',
                'emailAddress.description': 'string',
                'phoneNumber.number': 'required|string',
                'phoneNumber.description': 'string',
                'initialContribution': 'required|boolean',
                'contributionMinimumInitial': 'required|numeric|min:0',
                'contributionMinimumAdditional': 'required|numeric|min:0',
                'grantMinimumAmount': 'required|numeric|min:0',
                'grantFee': 'required|numeric|min:0',
                'certificateDeduction': 'required|numeric|min:0',
                'certificateFee': 'required|numeric|min:0',
                'extraBookletPercentage': 'numeric|min:0',
                'lineOfCredit': 'required|numeric|min:0',
                'blankBookletMax': 'numeric|min:0',
                'notificationLimitRemainderAmount': 'numeric',
                'sendWelcomeEmail': 'boolean',
                'isApproved': 'boolean'
            },

            types: {
                'initialContribution': 'checkbox',
                'sendWelcomeEmail': 'checkbox',
                'isApproved': 'checkbox',
            },

            options: {
                'donorAccount.phoneNumber.number': {
                    validateOnChange: true
                },
                'securityPin': {
                    validateOnChange: true
                }
            }
        };
    }
};